# Shared configurations
data:
  raw_data: "data/raw/imdb_four_genre_plots.csv"  # Match your actual filename
  processed_text: "data/processed/text/"
  test_size: 0.2
  random_state: 42

preprocessing:
  text:
    max_seq_length: 512       # For later transformer models
    min_word_count: 3         # For Word2Vec
    nltk_resources: ["punkt", "wordnet", "stopwords"]